name: Deploy container registry and docker image

concurrency: container-deploy-workflow

env:
  RESOURCEGROUP_NAME: container-rg-test
  REGISTRY_NAME: containeracrpch
  SHORT_NAME: contacrpch

permissions:
  id-token: write
  contents: read

on: 
  push:
    branches: 
      - main
  workflow_dispatch:
      
jobs:
  vars:
    runs-on: ubuntu-latest
    outputs:
      resource_group: ${{ env.RESOURCEGROUP_NAME }}
      acr_name: ${{ env.REGISTRY_NAME }}
      short_name: ${{ env.SHORT_NAME }}
    steps:
      - run: echo "Exposing env vars"

  deploy-acr:
    needs: vars
    uses: ./.github/workflows/deploy_acr.yml
    if: github.ref == 'refs/heads/main'
    with:
      environment: Prod
      resource_group: ${{ needs.vars.outputs.resource_group }}
      acr_name: ${{ needs.vars.outputs.acr_name }}

    secrets:
      azure_credentials: ${{ secrets.AZURE_CREDENTIALS }}

  build-push-container:
    needs: deploy-acr
    uses: ./.github/workflows/build_push_container.yml
    if: github.ref == 'refs/heads/main'
    with:
      environment: Prod
      acr_name: ${{ needs.vars.outputs.acr_name }}
      short_name: ${{ needs.vars.outputs.short_name }}
      build_number: ${{ github.run_number }}




