name: Deploy container registry and instance - test

concurrency: container-deploy-workflow

env:
  RESOURCEGROUP_NAME: my-rg
  REGISTRY_NAME: my-cr
  SHORT_NAME: mycr
  ACI_NAME: my-ci-test
  ENVIRONMENT: test

permissions:
  id-token: write
  contents: read

on: 
  push:
    branches: 
      - main
  workflow_dispatch:
      
jobs:
  vars:
    runs-on: ubuntu-latest
    outputs:
      resource_group: ${{ env.RESOURCEGROUP_NAME }}
      acr_name: ${{ env.REGISTRY_NAME }}
      short_name: ${{ env.SHORT_NAME }}
      aci_name: ${{ env.ACI_NAME }}
      environment: ${{ env.ENVIRONMENT }}
    steps:
      - run: echo "Exposing env vars"

  deploy-acr:
    needs: vars
    uses: ./.github/workflows/deploy_acr.yml
    if: github.ref == 'refs/heads/main'
    with:
      environment: ${{ needs.vars.outputs.environment }}
      resource_group: ${{ needs.vars.outputs.resource_group }}
      acr_name: ${{ needs.vars.outputs.acr_name }}
    secrets:
      azure_credentials: ${{ secrets.AZURE_CREDENTIALS }}

  build-push-container:
    needs: [vars, deploy-acr]
    uses: ./.github/workflows/build_push_container.yml
    if: github.ref == 'refs/heads/main'
    with:
      environment: ${{ needs.vars.outputs.environment }}
      acr_name: ${{ needs.vars.outputs.acr_name }}
      short_name: ${{ needs.vars.outputs.short_name }}
      build_number: ${{ github.run_number }}
    secrets:
      azure_credentials: ${{ secrets.AZURE_CREDENTIALS }}

  deploy-aci:
    needs: [vars, deploy-acr, build-push-container]
    uses: ./.github/workflows/deploy_aci.yml
    if: github.ref == 'refs/heads/main'
    with:
      environment: ${{ needs.vars.outputs.environment }}
      resource_group: ${{ needs.vars.outputs.resource_group }}
      acr_name: ${{ needs.vars.outputs.acr_name }}
      short_name: ${{ needs.vars.outputs.short_name }}
      aci_name: ${{ needs.vars.outputs.aci_name }}
    secrets:
      azure_credentials: ${{ secrets.AZURE_CREDENTIALS }}


