name: Deploy container registry and docker image

concurrency: container-deploy-workflow

env:
    RESOURCEGROUP_NAME: container-rg
    REGISTRY_NAME: container-acr

on: 
  push:
    branches: 
      - main
  workflow_dispatch:
      
jobs:

  deploy-acr-test:
    uses: ./.github/workflows/deploy_acr.yml
    if: github.ref == 'refs/heads/main'
    with:
      environment: Test
      resource_group: ${{ env.RESOURCEGROUP_NAME }}
      acr_name: ${{ env.REGISTRY_NAME }}
      creds: ${{ secrets.AZURE_CREDENTIALS_TEST }}

  deploy-acr-prod:
    needs: deploy-acr-test
    uses: ./.github/workflows/deploy_acr.yml
    if: github.ref == 'refs/heads/main'
    with:
      environment: Prod
      resource_group: ${{ env.RESOURCEGROUP_NAME }}-Prod
      acr_name: ${{ env.REGISTRY_NAME }}-Prod
      creds: ${{ secrets.AZURE_CREDENTIALS_PROD }}
